name:                monad-parser
version:             0.1.0.0
github:              "value/monad-parser"
license:             BSD3
author:              "James"
maintainer:          "value"
copyright:           "value"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            value

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/value/monad-parser#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  monad-parser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monad-parser

tests:
  monad-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monad-parser
